blogs/urls.py
from django.conf.urls import url, include

from blogs.views import BlogListView, BlogDetailView

app_name = 'blogs'

urlpatterns = [
    url(r'^$', BlogListView.as_view(), name='blog-list'),
    url(r'^(?P<slug>[\w-]+)/$', BlogDetailView.as_view(), name='blog-detail'),
    url(r'^comments/', include("comments.urls", namespace='comments')),
]

hexanovate/urls.py
from django.conf.urls import url

from hexanovate.views import ContactMessagePostView, SubscribeView, QuestionPostView

app_name = 'hexanovate'

urlpatterns = [
    url(r'^question/post/$', QuestionPostView.as_view(), name='post-question'),
    url(r'^contact-us/post/$', ContactMessagePostView.as_view(), name='post-contact-message'),
    url(r'^subscribe/$', SubscribeView.as_view(), name='subscribe')
]

hexanovate_website/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from accounts.views import signup,signin,logout

from hexanovate_website.views import (
    HomePageView, AboutPageView, PortfolioPageView,
    GalleryPageView, ContactUsPageView
)

urlpatterns = [
    path('google-auth/', TemplateView.as_view(template_name="google-auth.html")),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    path('signup/',signup),
    path('signin/',signin),
    path('logout/',logout),
   

    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^about/$', AboutPageView.as_view(), name='about'),
    url(r'^portfolio/$', PortfolioPageView.as_view(), name='portfolio'),
    url(r'^gallery/$', GalleryPageView.as_view(), name='gallery'),
    url(r'^contact-us/$', ContactUsPageView.as_view(), name='contact-us'),

    url(r'^', include("hexanovate.urls", namespace='hexanovate')),
    url(r'^blogs/', include("blogs.urls", namespace='blogs')),
    url(r'^resources/', include("resources.urls", namespace='resources')),
    url(r'^products/',include('product.urls',namespace='product')),
    
    path('sumernote/',include('django_summernote.urls'))
]

admin.site.site_header = "Hexanovate Administration"
admin.site.site_title = "Hexanovate Admin Portal"
admin.site.index_title = "Welcome to Hexanovate Admin Portal"

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import ProductView

app_name= 'product'

urlpatterns=[

   url(r'^$',ProductView,name='products'),
]









if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resources/urls.py
from django.conf.urls import url

from resources.views import ResourceListView

app_name = 'resources'

urlpatterns = [
    url(r'^$', ResourceListView.as_view(), name='resource-list'),
]

blogs/models.py
import os
import random

from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse
from django_ckeditor_5.fields import CKEditor5Field

from hexanovate.utils import unique_slug_generator


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    new_filename = random.randint(1, 3910209312)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "blogs/{new_filename}/{final_filename}".format(
        new_filename=new_filename,
        final_filename=final_filename
    )


class Category(models.Model):
    title = models.CharField(max_length=128)

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(max_length=128)

    def __str__(self):
        return self.title


class Blog(models.Model):
    title = models.CharField(max_length=128)
    slug = models.SlugField(blank=True, unique=True, max_length=128)
    thumbnail = models.ImageField(upload_to=upload_image_path)
    category = models.ForeignKey(Category, blank=True, null=True, related_name='blogs', on_delete=models.CASCADE)
    author = models.CharField(max_length=128)
    short_description = models.TextField()
    content = models.TextField()
    tags = models.ManyToManyField(Tag, related_name='blogs', blank=True)
    related_blogs = models.ManyToManyField('self', symmetrical=False, blank=True, related_name='related_blogs_reverse')
    active = models.BooleanField(default=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=('-date',)
        

    def get_absolute_url(self):
        return reverse("blogs:" + "blog-detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    @property
    def name(self):
        return self.title


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(product_pre_save_receiver, sender=Blog)

templates/base/chaticon.html
<div class="chaticon">
    <a href="#"><img src="https://img.icons8.com/flat_round/44/000000/filled-chat.png">
 </a>
</div>

templates/base/css.html
{% load static %}

<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,600,700,800,900&display=swap"
      rel="stylesheet">

<link href="{% static 'css/open-iconic-bootstrap.min.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/animate.css' %}">

<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

<link rel="stylesheet" href="{% static 'css/aos.css' %}">

<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

<link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
<link rel="stylesheet" href="{% static 'css/social-auth.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-151906126-1"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-151906126-1');
</script>
<!--Google add sense-->
<script data-ad-client="ca-pub-7276343634771824" async
        src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

templates/base/footer.html
<footer class="ftco-footer ftco-bg-dark ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-6 col-lg-3">
                <div class="ftco-footer-widget mb-5">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">
                                    89/412 Nehru nagar, Mohadi Road, Near Mehrun lake, Jalgaon</span>
                            </li>
                            <li>
                                <a href="#"><span class="icon icon-phone"></span><span
                                            class="text">+91 7820932512</span>
                                </a>
                            </li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">hexanovate@gmail.com</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="ftco-footer-widget mb-5">
                    <h2 class="ftco-heading-2">Recent Blog</h2>
                    {% for blog in recent_blogs %}
						{% if forloop.counter < 3 %}
                        <div class="block-21 mb-4 d-flex">
                            <a href="{{ blog.get_absolute_url }}" class="blog-img mr-4" style="background-image: url({{ blog.thumbnail.url }});"></a>
                            <div class="text">
                                <h3 class="heading"><a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a></h3>
                                <div class="meta">
                                    <div>
                                       
                                    </div>
                                    <div>
                                       
                                    </div>
                                    <!-- <div><a href="#"><span class="icon-chat"></span> 19</a></div> -->
                                </div>
                            </div>
                        </div>
						{% endif %}
					{% endfor %}
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="ftco-footer-widget mb-5 ml-md-4">
                    <h2 class="ftco-heading-2">Links</h2>
                    <ul class="list-unstyled">
                        <li><a href="/"><span class="ion-ios-arrow-round-forward mr-2"></span>Home</a></li>
                        <li><a href="/about"><span class="ion-ios-arrow-round-forward mr-2"></span>About</a></li>
                        <li><a href="/portfolio"><span class="ion-ios-arrow-round-forward mr-2"></span>Portfolio</a>
                        </li>
                        <li><a href="/#services"><span class="ion-ios-arrow-round-forward mr-2"></span>Services</a>
                        </li>
                        <li><a href="/blogs"><span class="ion-ios-arrow-round-forward mr-2"></span>Blogs</a></li>
                        <li><a href="/contact-us"><span class="ion-ios-arrow-round-forward mr-2"></span>Contact Us</a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="col-md-6 col-lg-3">
                <div class="ftco-footer-widget mb-5">
                    <h2 class="ftco-heading-2">Subscribe Us!</h2>
                    <form action="{% url 'hexanovate:subscribe' %}" method="post" class="subscribe-form">
						{% csrf_token %}
                        <div class="form-group">
                            <input name="email" type="email" class="form-control mb-2 text-center" placeholder="Enter email address">
                            <input type="submit" value="Subscribe" class="form-control submit px-3">
                        </div>
                    </form>
                </div>

                <div class="ftco-footer-widget mb-5">
                    <h2 class="ftco-heading-2 mb-0">Connect With Us</h2>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-3">
                        <li class="ftco-animate"><a href="https://twitter.com/hexanovate"><span
                                        class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="https://www.facebook.com/hexanovate/"><span
                                        class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="https://www.instagram.com/hexanovate/"><span
                                        class="icon-instagram"></span></a></li>
                        <li class="ftco-animate"><a href="https://www.linkedin.com/company/hexanovate/"><span
                                        class="icon-linkedin"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p>&copy; &nbsp;All rights reserved, Hexanovate</p>
            </div>
        </div>
    </div>
</footer>

templates/base/get-in-touch.html
{% load static %}

<section class="ftco-intro ftco-no-pb img" style="background-image: url({% static 'images/bg_1.jpg' %});">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-9 col-md-8 d-flex align-items-center heading-section heading-section-white ftco-animate">
                <h2 class="mb-3 mb-md-0">{{ data }}</h2>
            </div>
            <div class="col-lg-3 col-md-4 ftco-animate">
                <p class="mb-0"><a href="/contact-us" class="btn btn-white py-3 px-4">Get in touch with us</a></p>
            </div>
        </div>
    </div>
</section>

templates/base/hero-banner.html
{% load static %}


<section class="hero-wrap hero-wrap-3" style="background-image: url('{% static 'images/bg_1.jpg' %}');"
         data-stellar-background-ratio="0.5">
    <div class="overlay"></div>

    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center" data-scrollax-parent="true">
            <div class="col-md-9 ftco-animate text-center">

                <h1 class="mb-2"><span>We know, what you need.</span></h1>
                <br>
                <h3><span>Grow your Business with our Innovative Software and Marketing Solutions</span></h3>
                <br>
                <p><a href="/contact-us" class="btn btn-primary px-4 py-3 mt-3">Feel Free to Call</a></p>
            </div>
        </div>
    </div>
</section>

templates/base/loader.html
<!-- loader -->
{% comment %} <div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"></circle>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#080f5b"></circle>
    </svg>
</div> {% endcomment %}

templates/base/navbar.html
{% load static %}


{% url 'about' as about %}
{% url 'portfolio' as portfolio %}
{% url 'blogs:blog-list' as blog_list %}
{% url 'resources:resource-list' as resource_list %}
{% url 'gallery' as gallery %}
{% url 'contact-us' as contact_us %}
{% url 'product:products' as products %}

<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    
        <a class="navbar-brand" href="/">
            <img src="{% static 'images/hex_final.png' %}" width="160" height="60" >
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav">
                
                <li class="nav-item {% if request.path == about %}active{% endif %}"><a href="{{ about }}"
                                                                                        class="nav-link">About Us</a></li>
                <li class="nav-item {% if request.path == portfolio %}active{% endif %}"><a href="{{ portfolio }}"
                                                                                            class="nav-link">Portfolio</a>
                </li>

                 <li class="nav-item {% if request.path == products %}active{% endif %}"><a href="{{ products }}"
                    class="nav-link">Products</a>
                    </li>  

                <li class="nav-item {% if request.path == '/#services' %}active{% endif %}"><a href="/#services"
                                                                                               class="nav-link">Services</a>
                </li>
                <!-- <li class="nav-item"><a href="blog.html" class="nav-link">Blog</a></li> -->
                <li class="nav-item dropdown {% if request.path == blog_list %}active{% endif %}">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Blog
                    </a>
                    <div class="dropdown-menu text-center" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ blog_list }}">Blog Posts</a>
                        <a class="dropdown-item" href="{{ resource_list }}">Resources</a>
                    </div>
                </li>
                {% comment %} <li class="nav-item {% if request.path == gallery %}active{% endif %}">
                    <a href="{{ gallery }}" class="nav-link">Gallery</a>
                </li> {% endcomment %}
                <li class="nav-item ">
                    <a href="{{ contact_us }}" class="nav-link">Contact Us</a>
                </li>              
                {% comment %} {% include 'signup.html' %} {% endcomment %}
            
                {% comment %}<li class="nav-item">
                    <button class="loginBtn loginBtn--google">
                        Sign In with Google
                    </button>
                </li>{% endcomment %}
            </ul>

            <!--
            <ul class="navbar-nav">
                
                
                {% if request.user.is_authenticated %}
				<li class="nav-item"><a  href="/signup/" data-signin="login" class="nav-link" >{{request.user}}</a></li>
				<li class="nav-item"><a  href="#0" data-signin="login" class="nav-link">log out</a></li>
				{% else %}
				<li class="nav-item" ><a  href="#0" data-signin="login" class="nav-link">Sign in</a></li>
				<li class="nav-item"><a  href="#0" data-signin="signup" class="nav-link">Sign up</a></li>
				{% endif %}
                
                {% comment %} {% include 'signup.html' %} {% endcomment %}
            
                {% comment %}<li class="nav-item">
                    <button class="loginBtn loginBtn--google">
                        Sign In with Google
                    </button>
                </li>{% endcomment %}
            </ul>-->
        </div>
    
</nav>

templates/base/phone.html
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
<div class="phoneicon">
    
    <a href='#'><i class="fas fa-phone"></i><span style="color:black;"><b> Call us:</b></span> <span style="color:#c21807;">+91 7820932512</a>
</div>
<div class="chat">
    <br>
    <a href='#'><i class="fas fa-comment"></i></a>
</div>

templates/base/question.html
{% load static %}

<section class="ftco-section ftco-consult ftco-no-pt ftco-no-pb" style="background-image: url({% static 'images/bg_1.jpg' %})"
         data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 py-5 px-md-3">
                <div  class="py-md-3">
                    <div class="heading-section heading-section-white ftco-animate mb-5 ">
                        <h2 class="mb-4">Have any questions?</h2>
                        <p>Let us know your query.</p>
                    </div>
                    
                    <form action="{% url 'hexanovate:post-question' %}" method="post" class="appointment-form ftco-animate">
                        {% csrf_token %}
                        <div class="d-md-flex">
                            <div class="form-group">
                                <input name="Name" type="text" class="form-control" placeholder=" Name">
                            </div>
                            <div class="form-group ml-md-4">
                                <input name="E-mail" type="text" class="form-control" placeholder="E-mail">
                            </div>
                        </div>
                    
                        <div class="d-md-flex">
                            <div class="form-group">
                                <div class="form-field">
                                    <div class="select-wrap">
                                        <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                                        <select name="guidance" id="" class="form-control" placeholder="Select Guidance">
                                            <option value="Select Guidance">Select Guidance</option>
                                            <option value="Software Solutions">Software Solutions</option>
                                            <option value="Digital Marketing">Digital Marketing</option>
                                            <option value="Business">Business</option>
                                            <option value="Other Services">Other Services</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group ml-md-4">
                                <input name="phone" type="text" class="form-control" placeholder="Phone">
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <div class="form-group">
                                <textarea name="message" id="" cols="30" rows="2" class="form-control"
                                          placeholder="Message"></textarea>
                            </div>
                            <div class="form-group ml-md-4">
                                <input type="submit" value="Submit" class="btn btn-white py-3 px-4">
                            </div>
                        </div>
                    </form>
                
                </div>
            </div>
        </div>
    </div>
</section>

templates/base/scripts.html
{% load static %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{% static 'js/google-map.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

<script>
    function showNotification(from, align, msg, type) {

        $.notify({
            icon: 'error',
            message: msg

        }, {
            type: type,
            timer: 3000,
            placement: {
                from: from,
                align: align
            }
        });
    }

    $(document).ready(function () {
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'error' %}
                    showNotification("top", "right", "{{ message }}", "danger")
                {% elif message.tags == 'success' %}
                    showNotification("top", "right", "{{ message }}", "success")
                {% endif %}
            {% endfor %}
        {% endif %}
    });

</script>

templates/base/socialshare.html
<!-- Social Share Buttons-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
<div class="socialshare">
  
        
            <a class="facebook"href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}/">Facebook <i class="fab fa-facebook-square"></i></a>
            <a class="whatsapp" href="#">Whatsapp <i class="fab fa-whatsapp"></i></a>
            <a class="linkedin" href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{blog.title|title}}&source={{ request.build_absolute_uri }}">Linkedin <i class="fab fa-linkedin"></i></a>
            <a class="twitter" href="https://twitter.com/home?status=You%20should%20not%20miss%20this%20out...%20{{ request.build_absolute_uri }}">Twitter <i class="fab fa-twitter"></i></a>
        	
</div>

templates/base/work-with-us-banner.html
{% load static %}
<section class="ftco-intro ftco-no-pb img" style="background-image: url({% static 'images/bg_1.jpg' %});">
    <div class="container">
        <div class="row justify-content-center mb-5">
            <div class="col-md-10 text-center heading-section heading-section-white ftco-animate">
                <h2 class="mb-0">Why work with us</h2>
                <br>
                <p>We understand what our customer needs. Our optimal, integral and cost effective services keeps our
                    clients attached with us. For us customer satisfaction is of utmost importance.</p>
            </div>
            <br>
            <div class="iframe-container">
                <iframe width="1424" height="558" src="https://www.youtube.com/embed/F-Q2Et7CxD8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            <br>
            <div class="col-lg-3 col-md-4 ftco-animate"><br>
                <p class="mb-0"><a href="/about" class="btn btn-white py-3 px-4">Hear more about Us</a></p>
            </div>
        </div>
    </div>
</section>