blogs/urls.py
from django.conf.urls import url, include

from blogs.views import BlogListView, BlogDetailView

app_name = 'blogs'

urlpatterns = [
    url(r'^$', BlogListView.as_view(), name='blog-list'),
    url(r'^(?P<slug>[\w-]+)/$', BlogDetailView.as_view(), name='blog-detail'),
    url(r'^comments/', include("comments.urls", namespace='comments')),
]

hexanovate/urls.py
from django.conf.urls import url

from hexanovate.views import ContactMessagePostView, SubscribeView, QuestionPostView

app_name = 'hexanovate'

urlpatterns = [
    url(r'^question/post/$', QuestionPostView.as_view(), name='post-question'),
    url(r'^contact-us/post/$', ContactMessagePostView.as_view(), name='post-contact-message'),
    url(r'^subscribe/$', SubscribeView.as_view(), name='subscribe')
]

hexanovate_website/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from accounts.views import signup,signin,logout

from hexanovate_website.views import (
    HomePageView, AboutPageView, PortfolioPageView,
    GalleryPageView, ContactUsPageView
)

urlpatterns = [
    path('google-auth/', TemplateView.as_view(template_name="google-auth.html")),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    path('signup/',signup),
    path('signin/',signin),
    path('logout/',logout),
   

    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^about/$', AboutPageView.as_view(), name='about'),
    url(r'^portfolio/$', PortfolioPageView.as_view(), name='portfolio'),
    url(r'^gallery/$', GalleryPageView.as_view(), name='gallery'),
    url(r'^contact-us/$', ContactUsPageView.as_view(), name='contact-us'),

    url(r'^', include("hexanovate.urls", namespace='hexanovate')),
    url(r'^blogs/', include("blogs.urls", namespace='blogs')),
    url(r'^resources/', include("resources.urls", namespace='resources')),
    url(r'^products/',include('product.urls',namespace='product')),
    
    path('sumernote/',include('django_summernote.urls'))
]

admin.site.site_header = "Hexanovate Administration"
admin.site.site_title = "Hexanovate Admin Portal"
admin.site.index_title = "Welcome to Hexanovate Admin Portal"

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/contact/contact-form.html
{% url 'hexanovate:post-contact-message' as post_contact_message_url %}

<form action="{{ post_contact_message_url }}" method="post" class="bg-light p-5 contact-form">
	{% csrf_token %}
    <div class="form-group">
        <input name="name" type="text" class="form-control" placeholder="Your Name">
    </div>
    <div class="form-group">
        <input name="email" type="email" class="form-control" placeholder="Your Email">
    </div>
    <div class="form-group">
        <input name="subject" type="text" class="form-control" placeholder="Subject">
    </div>
    <div class="form-group">
        <textarea name="message" id="" cols="30" rows="7" class="form-control" placeholder="Message"></textarea>
    </div>
    <div class="form-group">
        <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
    </div>
</form>